import { DocumentTemplate } from '@/types';

export const documentTemplates: DocumentTemplate[] = [
  {
    id: 'strategic-report',
    name: 'Strategic Analysis Report',
    description: 'McKinsey-style strategic consulting report with executive summary, analysis, and recommendations',
    type: 'report',
    icon: 'TrendingUp',
    structure: [
      {
        id: 'executive-summary',
        title: 'Executive Summary',
        description: 'High-level overview of key findings and recommendations',
        required: true,
        placeholder: 'Summarize the key insights, findings, and recommended actions...',
        aiPrompt: 'Write a concise executive summary for a strategic consulting report about: {topic}. Include key findings, critical insights, and top 3 recommendations. Use professional business language.',
      },
      {
        id: 'situation-analysis',
        title: 'Situation Analysis',
        description: 'Current state assessment and market context',
        required: true,
        placeholder: 'Describe the current situation, market dynamics, and key challenges...',
        aiPrompt: 'Analyze the current situation for: {topic}. Include market context, competitive landscape, internal capabilities, and key challenges. Be specific and data-driven.',
      },
      {
        id: 'strategic-options',
        title: 'Strategic Options',
        description: 'Alternative strategies and their trade-offs',
        required: true,
        placeholder: 'Present strategic options with pros, cons, and risk assessments...',
        aiPrompt: 'Develop 3-4 strategic options for: {topic}. For each option, provide description, key benefits, potential risks, resource requirements, and timeline considerations.',
      },
      {
        id: 'recommendations',
        title: 'Recommendations',
        description: 'Prioritized action plan with implementation roadmap',
        required: true,
        placeholder: 'Detail recommended actions with priority levels and timelines...',
        aiPrompt: 'Provide detailed recommendations for: {topic}. Include prioritized action items, success metrics, resource allocation, risk mitigation strategies, and a phased implementation roadmap.',
      },
      {
        id: 'appendix',
        title: 'Supporting Analysis',
        description: 'Detailed data, methodology, and additional context',
        required: false,
        placeholder: 'Include detailed analysis, data tables, or methodology notes...',
        aiPrompt: 'Create supporting analysis content for: {topic}. Include methodology notes, detailed data breakdowns, and additional context that supports the main recommendations.',
      },
    ],
  },
  {
    id: 'policy-document',
    name: 'Policy Framework Document',
    description: 'World Bank/UN-style policy document with context, analysis, and policy recommendations',
    type: 'policy',
    icon: 'Globe',
    structure: [
      {
        id: 'background',
        title: 'Background & Context',
        description: 'Historical context and policy landscape',
        required: true,
        placeholder: 'Provide background information and policy context...',
        aiPrompt: 'Write the background section for a policy document about: {topic}. Include historical context, current policy landscape, key stakeholders, and the rationale for policy intervention.',
      },
      {
        id: 'problem-statement',
        title: 'Problem Statement',
        description: 'Clear articulation of the policy challenge',
        required: true,
        placeholder: 'Define the problem clearly with supporting evidence...',
        aiPrompt: 'Articulate the policy problem for: {topic}. Include problem definition, root causes, affected populations, scale and scope, and the cost of inaction. Use evidence-based arguments.',
      },
      {
        id: 'policy-analysis',
        title: 'Policy Analysis',
        description: 'Evidence-based analysis of policy options',
        required: true,
        placeholder: 'Analyze different policy approaches and their implications...',
        aiPrompt: 'Conduct policy analysis for: {topic}. Compare different policy approaches, assess effectiveness, efficiency, equity, and political feasibility. Include international best practices and lessons learned.',
      },
      {
        id: 'recommendations',
        title: 'Policy Recommendations',
        description: 'Specific policy proposals with implementation guidance',
        required: true,
        placeholder: 'Present policy recommendations with implementation steps...',
        aiPrompt: 'Develop policy recommendations for: {topic}. Include specific policy proposals, implementation mechanisms, institutional arrangements, monitoring frameworks, and success indicators.',
      },
      {
        id: 'implementation',
        title: 'Implementation Framework',
        description: 'Detailed implementation plan and timeline',
        required: false,
        placeholder: 'Outline implementation steps, timeline, and responsibilities...',
        aiPrompt: 'Create an implementation framework for: {topic}. Include phased approach, key milestones, stakeholder responsibilities, resource requirements, and risk management strategies.',
      },
    ],
  },
  {
    id: 'business-proposal',
    name: 'Business Proposal',
    description: 'Professional business proposal with problem definition, solution, and commercial terms',
    type: 'proposal',
    icon: 'Briefcase',
    structure: [
      {
        id: 'introduction',
        title: 'Introduction',
        description: 'Company introduction and proposal overview',
        required: true,
        placeholder: 'Introduce your organization and the purpose of this proposal...',
        aiPrompt: 'Write a compelling introduction for a business proposal about: {topic}. Include brief company overview, understanding of client needs, and value proposition preview.',
      },
      {
        id: 'problem-opportunity',
        title: 'Problem / Opportunity',
        description: 'Clear definition of the challenge or opportunity',
        required: true,
        placeholder: 'Define the problem or opportunity being addressed...',
        aiPrompt: 'Describe the problem or opportunity for: {topic}. Demonstrate deep understanding of the challenge, quantify the impact, and create urgency for action.',
      },
      {
        id: 'proposed-solution',
        title: 'Proposed Solution',
        description: 'Detailed description of your solution and approach',
        required: true,
        placeholder: 'Describe your solution, methodology, and unique approach...',
        aiPrompt: 'Detail the proposed solution for: {topic}. Include approach overview, methodology, key features, deliverables, and what makes this solution uniquely effective.',
      },
      {
        id: 'timeline-milestones',
        title: 'Timeline & Milestones',
        description: 'Project schedule with key deliverables',
        required: true,
        placeholder: 'Outline the project timeline with major milestones...',
        aiPrompt: 'Create a realistic project timeline for: {topic}. Include project phases, key milestones, deliverables, dependencies, and checkpoints for review.',
      },
      {
        id: 'investment-terms',
        title: 'Investment & Terms',
        description: 'Pricing, terms, and conditions',
        required: true,
        placeholder: 'Present pricing structure and commercial terms...',
        aiPrompt: 'Outline the investment and terms section for: {topic}. Include pricing structure, payment terms, what is included/excluded, guarantees, and next steps to proceed.',
      },
    ],
  },
  {
    id: 'executive-presentation',
    name: 'Executive Presentation',
    description: 'High-impact presentation deck for C-suite audiences',
    type: 'presentation',
    icon: 'Presentation',
    structure: [
      {
        id: 'title-agenda',
        title: 'Title & Agenda',
        description: 'Opening slide with clear agenda',
        required: true,
        placeholder: 'Set the stage with a compelling title and clear agenda...',
        aiPrompt: 'Create an engaging title slide and agenda for a presentation about: {topic}. Include a powerful headline, 4-5 agenda items, and expected outcomes.',
      },
      {
        id: 'key-message',
        title: 'Key Message',
        description: 'The single most important takeaway',
        required: true,
        placeholder: 'What is the one thing your audience must remember?',
        aiPrompt: 'Craft the key message slide for: {topic}. Create a powerful, memorable statement that captures the essence of your presentation in one impactful sentence.',
      },
      {
        id: 'situation',
        title: 'Current Situation',
        description: 'Context and background with data',
        required: true,
        placeholder: 'Present the current situation with supporting data...',
        aiPrompt: 'Describe the current situation for: {topic}. Include key data points, market context, and critical observations. Keep it concise and visually oriented.',
      },
      {
        id: 'analysis',
        title: 'Analysis & Insights',
        description: 'Key findings and insights',
        required: true,
        placeholder: 'Share your analysis and the insights derived from it...',
        aiPrompt: 'Present analysis and insights for: {topic}. Include 3-4 key findings, data visualization suggestions, and the "so what" for each insight.',
      },
      {
        id: 'recommendation',
        title: 'Recommendation',
        description: 'Clear, actionable recommendations',
        required: true,
        placeholder: 'Present your recommendations clearly and persuasively...',
        aiPrompt: 'Develop recommendations for: {topic}. Present 2-3 clear recommendations with expected impact, required resources, and timeline. Make it actionable.',
      },
      {
        id: 'next-steps',
        title: 'Next Steps & Ask',
        description: 'Clear call to action',
        required: true,
        placeholder: 'Define specific next steps and what you need from the audience...',
        aiPrompt: 'Create the next steps slide for: {topic}. Include immediate actions, decision points, resource requests, and a clear call to action for the audience.',
      },
    ],
  },
  {
    id: 'market-research',
    name: 'Market Research Report',
    description: 'Comprehensive market analysis with trends, competitive landscape, and opportunities',
    type: 'report',
    icon: 'BarChart',
    structure: [
      {
        id: 'executive-overview',
        title: 'Executive Overview',
        description: 'High-level summary of market findings',
        required: true,
        placeholder: 'Summarize key market findings and implications...',
        aiPrompt: 'Write an executive overview for market research on: {topic}. Include market size, growth rate, key trends, and strategic implications.',
      },
      {
        id: 'market-overview',
        title: 'Market Overview',
        description: 'Market size, growth, and segmentation',
        required: true,
        placeholder: 'Describe market size, segments, and growth dynamics...',
        aiPrompt: 'Provide a comprehensive market overview for: {topic}. Include total addressable market, served addressable market, market segments, growth rates, and key drivers.',
      },
      {
        id: 'competitive-landscape',
        title: 'Competitive Landscape',
        description: 'Key players, market share, and positioning',
        required: true,
        placeholder: 'Analyze major competitors and their market positions...',
        aiPrompt: 'Analyze the competitive landscape for: {topic}. Include major players, market share estimates, competitive positioning, strengths/weaknesses, and recent strategic moves.',
      },
      {
        id: 'trends-drivers',
        title: 'Trends & Drivers',
        description: 'Key market trends and growth drivers',
        required: true,
        placeholder: 'Identify and analyze major market trends...',
        aiPrompt: 'Identify key trends and drivers for: {topic}. Include macro trends, technology trends, regulatory changes, consumer behavior shifts, and their implications.',
      },
      {
        id: 'opportunities-threats',
        title: 'Opportunities & Threats',
        description: 'Strategic opportunities and potential risks',
        required: true,
        placeholder: 'Highlight key opportunities and threats in the market...',
        aiPrompt: 'Assess opportunities and threats in: {topic}. Include emerging opportunities, market gaps, potential threats, disruption risks, and strategic recommendations.',
      },
    ],
  },
];

export function getTemplateById(id: string): DocumentTemplate | undefined {
  return documentTemplates.find((template) => template.id === id);
}

export function getTemplatesByType(type: string): DocumentTemplate[] {
  return documentTemplates.filter((template) => template.type === type);
}
